Medicine.create(name: 'Fluimucil', value: 6.5, stock: 43)
Medicine.create(name: 'Probiatop', value: 24.46, stock: 36)
Medicine.create(name: 'Colflex Bio', value: 58.72, stock: 34)
Medicine.create(name: 'Addera D3 Comprimido', value: 20.68, stock: 20)
Customer.create(name: 'beatriz oliveira')
Customer.create(name: 'joão da silva')
